### ISSUE TITLE
Link to .NEXT library

### ISSUE THREAD

**Issue by sakno** [Insvald/Slik#13]
Hi @Insvald ,

.NEXT project has been transferred to .NET Foundation. Could you please fix the link to it?

Old location: https://github.com/sakno/dotNext
New location: https://github.com/dotnet/dotNext

Thanks in advance!

**Comment by Insvald** [comment]
Thanks for the update! Done: https://github.com/Insvald/Slik/commit/927dae304561fbe6c823eec95db021a73843cc9b
